name: Ticket System Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Bandit
        uses: tj-actions/bandit@v5.1
        with:
          targets: |
            ticket_website
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Pytest Plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Test with PyTest
        run: |
          pytest